# Generated by Django 5.1.15 on 2026-03-06 06:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
        ('products', '0004_productvariant_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='quantity_ml',
            field=models.PositiveIntegerField(default=0, help_text='ML size at time of purchase'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='variant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_items', to='products.productvariant'),
        ),
    ]
