# Generated by Django 5.1.15 on 2026-03-07 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_orderitem_quantity_ml_orderitem_variant'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='razorpay_order_id',
            field=models.CharField(blank=True, help_text='Razorpay order ID (order_xxxxxxxx)', max_length=100, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='razorpay_payment_id',
            field=models.CharField(blank=True, help_text='Razorpay payment ID (pay_xxxxxxxx)', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='razorpay_signature',
            field=models.CharField(blank=True, help_text='Razorpay HMAC signature for verification', max_length=300, null=True),
        ),
    ]
