# Generated by Django 5.1.15 on 2026-03-11 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_add_razorpay_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='selected_origin',
            field=models.CharField(default='india', help_text='Origin selected at purchase', max_length=20),
        ),
    ]
