# Generated by Django 5.1.15 on 2026-03-24 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_order_gst_amount_order_shipping_fee'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='tester_box_items',
            field=models.JSONField(blank=True, default=list, help_text='Snapshot of variant IDs selected for custom tester boxes'),
        ),
    ]
