# Generated by Django 5.1.15 on 2026-02-27 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='quantity_ml',
            field=models.PositiveIntegerField(default=100, help_text='Bottle size in millilitres (e.g. 30, 50, 100)'),
        ),
    ]
