# Generated by Django 5.1.15 on 2026-03-05 10:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_product_quantity_ml'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productimage',
            options={'ordering': ['sort_order']},
        ),
        migrations.RemoveField(
            model_name='productimage',
            name='is_primary',
        ),
    ]
