# Generated by Django 5.1.15 on 2026-03-10 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_productvariant_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='inspired_by',
            field=models.CharField(blank=True, help_text="e.g. 'Our Creation Of Bdk\\'s Vanille Leather Perfume'", max_length=255),
        ),
    ]
