# Generated by Django 5.1.15 on 2026-03-11 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_product_inspired_by'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productvariant',
            old_name='price',
            new_name='india_price',
        ),
        migrations.RenameField(
            model_name='productvariant',
            old_name='discount_price',
            new_name='india_discount_price',
        ),
        migrations.AlterField(
            model_name='productvariant',
            name='india_price',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Price for India variant', max_digits=10),
        ),
        migrations.AlterField(
            model_name='productvariant',
            name='india_discount_price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Discount price for India variant', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='productvariant',
            name='switzerland_discount_price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Discount price for Switzerland variant', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='productvariant',
            name='switzerland_price',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Price for Switzerland variant', max_digits=10),
        ),
    ]
