# Generated by Django 5.1.15 on 2026-03-11 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_remove_productvariant_discount_price_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productvariant',
            name='stock',
        ),
        migrations.AddField(
            model_name='productvariant',
            name='india_stock',
            field=models.PositiveIntegerField(default=0, help_text='Stock for India variant'),
        ),
        migrations.AddField(
            model_name='productvariant',
            name='switzerland_stock',
            field=models.PositiveIntegerField(default=0, help_text='Stock for Switzerland variant'),
        ),
    ]
