# Generated by Django 5.1.15 on 2026-03-12 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_remove_productvariant_stock_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TesterBox',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(blank=True, max_length=120, unique=True)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('products', models.ManyToManyField(blank=True, related_name='tester_boxes', to='products.product')),
            ],
            options={
                'verbose_name_plural': 'tester boxes',
                'ordering': ['name'],
            },
        ),
    ]
