# Generated by Django 5.1.15 on 2026-03-13 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_testerbox'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='is_roll_on',
            field=models.BooleanField(db_index=True, default=False, help_text='If True, this product is a roll-on attar and will not appear in the main product listing.'),
        ),
    ]
