# Generated by Django 5.1.15 on 2026-03-23 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_add_is_roll_on_to_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='productvariant',
            name='oversell',
            field=models.CharField(choices=[('deny', 'Deny'), ('continue', 'Continue')], default='deny', help_text='Allow purchase when out of stock', max_length=10),
        ),
    ]
