# Generated by Django 5.1.15 on 2026-03-23 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_productvariant_oversell'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productvariant',
            name='india_price',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, help_text='Price for India variant', max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='productvariant',
            name='switzerland_price',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, help_text='Price for Switzerland variant', max_digits=10, null=True),
        ),
    ]
