# Generated by Django 5.1.15 on 2026-03-23 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0011_alter_productvariant_india_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productvariant',
            name='india_price',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Price for India variant', max_digits=10),
        ),
        migrations.AlterField(
            model_name='productvariant',
            name='switzerland_price',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Price for Switzerland variant', max_digits=10),
        ),
    ]
