# Generated by Django 5.1.15 on 2026-03-06 06:42

import django.db.models.deletion
from django.db import migrations, models


def clear_cart_items(apps, schema_editor):
    """Clear existing cart items before adding the variant FK."""
    CartItem = apps.get_model("cart", "CartItem")
    CartItem.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0001_initial'),
        ('products', '0004_productvariant_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='cartitem',
            unique_together=set(),
        ),
        # Clear existing cart items so the new FK doesn't violate constraints
        migrations.RunPython(clear_cart_items, migrations.RunPython.noop),
        migrations.AddField(
            model_name='cartitem',
            name='variant',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='cart_items', to='products.productvariant'),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='cartitem',
            unique_together={('cart', 'variant')},
        ),
    ]
