# Generated by Django 5.1.15 on 2026-03-11 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0002_alter_cartitem_unique_together_cartitem_variant_and_more'),
        ('products', '0006_remove_productvariant_discount_price_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='cartitem',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='cartitem',
            name='selected_origin',
            field=models.CharField(choices=[('india', 'India'), ('switzerland', 'Switzerland')], default='india', max_length=20),
        ),
        migrations.AlterUniqueTogether(
            name='cartitem',
            unique_together={('cart', 'variant', 'selected_origin')},
        ),
    ]
