# Generated by Django 5.1.15 on 2026-03-24 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0003_alter_cartitem_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='tester_box_items',
            field=models.JSONField(blank=True, default=list, help_text='List of variant IDs selected for custom tester boxes'),
        ),
    ]
